# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 263ed6af74966eb3c6df965962a3b2f25ce5ba47996b5e95847f4a8e93790594baa624e4cc40b9e3fb9383ab55fa3ccc09f92a86b2fda9ffc478e0d77409b7fa

test:
  secret_key_base: dfc95675199bb1288c738628b034277d4c09d7e183b21dd3ea1132dcf0156da9d522fac9f716d818626cba6c65b92b506c28bea74916c084b9bcad344fad0fcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
